Purpose :
To predict the underwater ROCK or Explosive MINE .

Description :
The dataset contains a set of 208 records under 60 attributes - Data consist of sonar signals either bounced off a metal cylinder or bounced off a roughly cylindrical rock and Class(R - Rock , M - Mine).

STEP 1 : Load all the necessary libraries

In [1]:
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
import pandas as pd
import numpy as np
pd.set_option('display.max_rows',None)
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [2]:
df = pd.read_csv("sonar.csv",header=None)

In [3]:
df

0       1       2       3       4   ...      56      57      58      59  60
0    0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1    0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2    0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3    0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4    0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R
5    0.0286  0.0453  0.0277  0.0174  0.0384  ...  0.0057  0.0027  0.0051  0.0062   R
6    0.0317  0.0956  0.1321  0.1408  0.1674  ...  0.0092  0.0143  0.0036  0.0103   R
7    0.0519  0.0548  0.0842  0.0319  0.1158  ...  0.0085  0.0047  0.0048  0.0053   R
8    0.0223  0.0375  0.0484  0.0475  0.0647  ...  0.0065  0.0093  0.0059  0.0022   R
9    0.0164  0.0173  0.0347  0.0070  0.0187  ...  0.0032  0.0035  0.0056  0.0040   R
10   0.0039  0.0063  0.0152  0.0336  0.0310  ...  0.0042  0.0003  0.0053  0.0036   R
11   0.0123  0.0309  0.0169  0.0313  0.0358  ...  0.0026  0.0092  0.0009  0.0044   R
12   0.0079  0.0086  0.0055  0.0250  0.0344  ...  0.0059  0.0058  0.0059  0.0032   R
13   0.0090  0.0062  0.0253  0.0489  0.1197  ...  0.0158  0.0053  0.0189  0.0102   R
14   0.0124  0.0433  0.0604  0.0449  0.0597  ...  0.0114  0.0196  0.0147  0.0062   R
15   0.0298  0.0615  0.0650  0.0921  0.1615  ...  0.0152  0.0049  0.0200  0.0073   R
16   0.0352  0.0116  0.0191  0.0469  0.0737  ...  0.0095  0.0015  0.0073  0.0067   R
17   0.0192  0.0607  0.0378  0.0774  0.1388  ...  0.0045  0.0037  0.0112  0.0075   R
18   0.0270  0.0092  0.0145  0.0278  0.0412  ...  0.0120  0.0132  0.0070  0.0088   R
19   0.0126  0.0149  0.0641  0.1732  0.2565  ...  0.0181  0.0094  0.0116  0.0063   R
20   0.0473  0.0509  0.0819  0.1252  0.1783  ...  0.0049  0.0082  0.0028  0.0027   R
21   0.0664  0.0575  0.0842  0.0372  0.0458  ...  0.0024  0.0162  0.0109  0.0079   R
22   0.0099  0.0484  0.0299  0.0297  0.0652  ...  0.0029  0.0160  0.0106  0.0134   R
23   0.0115  0.0150  0.0136  0.0076  0.0211  ...  0.0029  0.0037  0.0070  0.0041   R
24   0.0293  0.0644  0.0390  0.0173  0.0476  ...  0.0105  0.0160  0.0095  0.0011   R
25   0.0201  0.0026  0.0138  0.0062  0.0133  ...  0.0007  0.0024  0.0057  0.0044   R
26   0.0151  0.0320  0.0599  0.1050  0.1163  ...  0.0011  0.0019  0.0023  0.0062   R
27   0.0177  0.0300  0.0288  0.0394  0.0630  ...  0.0099  0.0057  0.0032  0.0019   R
28   0.0100  0.0275  0.0190  0.0371  0.0416  ...  0.0117  0.0020  0.0091  0.0058   R
29   0.0189  0.0308  0.0197  0.0622  0.0080  ...  0.0099  0.0092  0.0052  0.0075   R
30   0.0240  0.0218  0.0324  0.0569  0.0330  ...  0.0054  0.0019  0.0066  0.0023   R
31   0.0084  0.0153  0.0291  0.0432  0.0951  ...  0.0058  0.0031  0.0072  0.0045   R
32   0.0195  0.0213  0.0058  0.0190  0.0319  ...  0.0095  0.0095  0.0021  0.0053   R
33   0.0442  0.0477  0.0049  0.0581  0.0278  ...  0.0080  0.0105  0.0059  0.0105   R
34   0.0311  0.0491  0.0692  0.0831  0.0079  ...  0.0229  0.0182  0.0046  0.0038   R
35   0.0206  0.0132  0.0533  0.0569  0.0647  ...  0.0077  0.0180  0.0109  0.0070   R
36   0.0094  0.0166  0.0398  0.0359  0.0681  ...  0.0217  0.0087  0.0077  0.0122   R
37   0.0333  0.0221  0.0270  0.0481  0.0679  ...  0.0143  0.0132  0.0051  0.0041   R
38   0.0123  0.0022  0.0196  0.0206  0.0180  ...  0.0113  0.0058  0.0047  0.0071   R
39   0.0091  0.0213  0.0206  0.0505  0.0657  ...  0.0098  0.0043  0.0071  0.0108   R
40   0.0068  0.0232  0.0513  0.0444  0.0249  ...  0.0041  0.0052  0.0194  0.0105   R
41   0.0093  0.0185  0.0056  0.0064  0.0260  ...  0.0089  0.0050  0.0058  0.0025   R
42   0.0211  0.0319  0.0415  0.0286  0.0121  ...  0.0105  0.0049  0.0070  0.0080   R
43   0.0093  0.0269  0.0217  0.0339  0.0305  ...  0.0070  0.0116  0.0060  0.0110   R
44   0.0257  0.0447  0.0388  0.0239  0.1315  ...  0.0025  0.0199  0.0255  0.0180   R
45   0.0408  0.0653  0.0397  0.0604  0.0496  ...  0.0199  0.0102  0.0070  0.0055   R
46   0.0308  0


STEP 2 : Data Preparation

In [4]:
sonar = df.sample(frac = 1) 

In [5]:
sonar = sonar.values

In [6]:
sonar_xtrain = sonar[:124 , :60].astype('float')
sonar_xtrain.shape

(124, 60)

In [7]:
sonar_ytrain = sonar[:124 , 60]
sonar_ytrain.shape

(124,)

In [8]:
sonar_xtest = sonar[124: , :60].astype('float')
sonar_xtest.shape

(84, 60)

In [9]:
sonar_ytest = sonar[124: , 60]
sonar_ytest.shape

(84,)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
encoded_ytrain = le.fit_transform(sonar_ytrain)
encoded_ytrain

array([0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

Rock = 1 Mine = 0

In [11]:
encoded_ytest = le.fit_transform(sonar_ytest)
encoded_ytest

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1])



STEP 3 : Model Architecture 

In [12]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(60,)),     # Convert in 1D
    tf.keras.layers.Dense(60 , activation='relu'),   #  max(x,0)
    tf.keras.layers.Dense(1, activation = 'sigmoid')   # In binary we use sigmoid
])

STEP 4 : Compilation Step 

In [13]:
model.compile(optimizer='adam',
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])

In [14]:
model.fit(sonar_xtrain , encoded_ytrain , epochs = 300)

Epoch 1/300
4/4 [==============================] - 0s 2ms/step - loss: 0.7265 - accuracy: 0.5242
Epoch 2/300
4/4 [==============================] - 0s 2ms/step - loss: 0.6940 - accuracy: 0.5161
Epoch 3/300
4/4 [==============================] - 0s 2ms/step - loss: 0.6769 - accuracy: 0.5726
Epoch 4/300
4/4 [==============================] - 0s 2ms/step - loss: 0.6653 - accuracy: 0.6694
Epoch 5/300
4/4 [==============================] - 0s 2ms/step - loss: 0.6599 - accuracy: 0.6694
Epoch 6/300
4/4 [==============================] - 0s 1ms/step - loss: 0.6544 - accuracy: 0.6855
Epoch 7/300
4/4 [==============================] - 0s 2ms/step - loss: 0.6487 - accuracy: 0.6935
Epoch 8/300
4/4 [==============================] - 0s 2ms/step - loss: 0.6450 - accuracy: 0.6935
Epoch 9/300
4/4 [==============================] - 0s 1ms/step - loss: 0.6397 - accuracy: 0.6935
Epoch 10/300
4/4 [==============================] - 0s 2ms/step - loss: 0.6347 - accuracy: 0.7016
Epoch 11/300
4/4 [===========

STEP 5 : Evaluation

In [15]:
model.evaluate(sonar_xtest , encoded_ytest)

3/3 [==============================] - 0s 2ms/step - loss: 0.2972 - accuracy: 0.8929


[0.2972100079059601, 0.8928571343421936]

In [17]:
loss , acc = model.evaluate(sonar_xtest , encoded_ytest , verbose=2)

3/3 - 0s - loss: 0.2972 - accuracy: 0.8929


In [18]:
loss

0.2972100079059601

In [20]:
acc * 100 

89.28571343421936

In [33]:
sonar_xtest[25]

array([0.0238, 0.0318, 0.0422, 0.0399, 0.0788, 0.0766, 0.0881, 0.1143,
       0.1594, 0.2048, 0.2652, 0.31  , 0.2381, 0.1918, 0.143 , 0.1735,
       0.1781, 0.2852, 0.5036, 0.6166, 0.7616, 0.8125, 0.7793, 0.8788,
       0.8813, 0.947 , 1.    , 0.9739, 0.8446, 0.6151, 0.4302, 0.3165,
       0.2869, 0.2017, 0.1206, 0.0271, 0.058 , 0.1262, 0.1072, 0.1082,
       0.036 , 0.1197, 0.2061, 0.2054, 0.1878, 0.2047, 0.1716, 0.1069,
       0.0477, 0.017 , 0.0186, 0.0096, 0.0071, 0.0084, 0.0038, 0.0026,
       0.0028, 0.0013, 0.0035, 0.006 ])

In [35]:
i = 25
prediction = model.predict(sonar_xtest[i].reshape(1,60))
prediction

array([[0.00473297]], dtype=float32)

In [36]:
sonar_xtest[i]

array([0.0238, 0.0318, 0.0422, 0.0399, 0.0788, 0.0766, 0.0881, 0.1143,
       0.1594, 0.2048, 0.2652, 0.31  , 0.2381, 0.1918, 0.143 , 0.1735,
       0.1781, 0.2852, 0.5036, 0.6166, 0.7616, 0.8125, 0.7793, 0.8788,
       0.8813, 0.947 , 1.    , 0.9739, 0.8446, 0.6151, 0.4302, 0.3165,
       0.2869, 0.2017, 0.1206, 0.0271, 0.058 , 0.1262, 0.1072, 0.1082,
       0.036 , 0.1197, 0.2061, 0.2054, 0.1878, 0.2047, 0.1716, 0.1069,
       0.0477, 0.017 , 0.0186, 0.0096, 0.0071, 0.0084, 0.0038, 0.0026,
       0.0028, 0.0013, 0.0035, 0.006 ])

STEP 6 : Prediction

In [40]:
prediction

array([[0.00473297]], dtype=float32)

In [41]:
if  np.round(prediction) == 0 :
    print("The data is : ", sonar_xtest[i] , "and I have predicted that it's a :",prediction,"i.e Mine")
    print("Actual Data is : ",sonar_xtest[i], "Actual label" , sonar_ytest[i])
elif  np.round(prediction) == 1:
    print("The data is : ", sonar_xtest[i] , "and I have predicted that it's a :",prediction,"i.e Rock")
    print("Actual Data is : ",sonar_xtest[i], "Actual label" , sonar_ytest[i])


The data is :  [0.0238 0.0318 0.0422 0.0399 0.0788 0.0766 0.0881 0.1143 0.1594 0.2048
 0.2652 0.31   0.2381 0.1918 0.143  0.1735 0.1781 0.2852 0.5036 0.6166
 0.7616 0.8125 0.7793 0.8788 0.8813 0.947  1.     0.9739 0.8446 0.6151
 0.4302 0.3165 0.2869 0.2017 0.1206 0.0271 0.058  0.1262 0.1072 0.1082
 0.036  0.1197 0.2061 0.2054 0.1878 0.2047 0.1716 0.1069 0.0477 0.017
 0.0186 0.0096 0.0071 0.0084 0.0038 0.0026 0.0028 0.0013 0.0035 0.006 ] and I have predicted that it's a : [[0.00473297]] i.e Mine
Actual Data is :  [0.0238 0.0318 0.0422 0.0399 0.0788 0.0766 0.0881 0.1143 0.1594 0.2048
 0.2652 0.31   0.2381 0.1918 0.143  0.1735 0.1781 0.2852 0.5036 0.6166
 0.7616 0.8125 0.7793 0.8788 0.8813 0.947  1.     0.9739 0.8446 0.6151
 0.4302 0.3165 0.2869 0.2017 0.1206 0.0271 0.058  0.1262 0.1072 0.1082
 0.036  0.1197 0.2061 0.2054 0.1878 0.2047 0.1716 0.1069 0.0477 0.017
 0.0186 0.0096 0.0071 0.0084 0.0038 0.0026 0.0028 0.0013 0.0035 0.006 ] Actual label M
